# Tracey 3/2024:
# This is the adapted & simplified from:
# https://gitlab.com/gitlab-org/gitlab/-/raw/master/lib/gitlab/ci/templates/Jobs/Build.gitlab-ci.yml

variables:
  AUTO_BUILD_IMAGE_VERSION: 'v1.14.0'

build:
  stage: build
  # image: '${CI_TEMPLATE_REGISTRY_HOST}/gitlab-org/cluster-integration/auto-build-image:${AUTO_BUILD_IMAGE_VERSION}'
  image: registry.gitlab.com/internetarchive/auto-build-image/main:latest
  variables:
    DOCKER_TLS_CERTDIR: ''
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi


      if [ "$NOMAD_VAR_SERVERLESS" != "" ]; then
        # For IA SERVERLESS CI/CD pipelines, we only want to make (2nd) tag of `:latest` for our
        # built image *after* [test] phase runs successfully (since that's our logical deploy)
        echo "dont tag/push to :latest now -- save for [deploy-serverless] job"
        sed -i 's/docker push .*image_latest.*//' /build/build.sh
        sed -i      's/\-\-tag ..image_latest.//' /build/build.sh
      fi

    - /build/build.sh
  artifacts:
    reports:
      dotenv: gl-auto-build-variables.env
  rules:
    - if: '$BUILD_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
