on: [push, workflow_dispatch]
jobs:
  cicd:
    # https://github.com/internetarchive/cicd
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    with:
      NOMAD_VAR_HOSTNAMES: '["nomad.archive.org"]'
      NOMAD_VAR_MEMORY: 100 # xxx
      NOMAD_VAR_CHECK_PROTOCOL: 'tcp'
      BASE_DOMAIN: 'ext.archive.org'
    secrets:
      NOMAD_TOKEN_EXT: ${{ secrets.NOMAD_TOKEN_EXT }}
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: [cicd]
    container:
      # test using the just built-and-pushed docker image from the [cicd] job above
      image: 'docker://ghcr.io/${{ github.repository }}:${{ github.ref_name }}'
    steps:
    - run:  env -i zsh -euax test/test.sh
